{% set name = "graphtools" %}
{% set version = "1.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/KrishnaswamyLab/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 714f1777229cbac5b3475872f36fd3e0e14bfa3375b3597b193d5762df5deb0d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - future
    - numpy >=1.14.0
    - pygsp >=0.5.1
    - python >=3.5
    - scikit-learn >=0.20.0
    - scipy >=1.1.0
    - tasklogger >=1.0

test:
  imports:
    - graphtools

about:
  home: https://github.com/KrishnaswamyLab/graphtools
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: graphtools, tools for building and manipulating graphs in Python.

extra:
  recipe-maintainers:
    - bebatut
    - scottgigante
